core/urls.py
from tkinter.font import names
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('insumos.urls', namespace="insumos")),
    path('departamentos/', include('departamentos.urls', namespace="departamentos")),
    path('usuarios/', include('user.urls', namespace="usuarios")),
    path('formularios/', include('formularioInsumos.urls', namespace="formularios")),
    path('cargos/', include('cargos.urls', namespace="cargos")),
    path('formulariosr/', include('formularioSR.urls', namespace="formulariosr")),
    path('proveedores/', include('proveedores.urls', namespace="proveedores")),
    path('compras/', include('compras.urls', namespace="compras")),
    path('presupuesto/', include('presupuesto.urls', namespace="presupuestos")),
    path('cierremensual/', include('cierreMensual.urls', namespace="cierremensual")),
    path('configuraciones/', include('configuraciones.urls', namespace="configuraciones")),
    path('logs/', include('logs.urls', namespace="logs")),
    path('inventario/', include('inventario.urls', namespace="inventario")),
    path('reportes/', include('reportes.urls', namespace="reportes")),
]


handler404 = 'user.views.error_404'
handler403 = 'user.views.error_403'

formularioInsumos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import FormularioInsumoCreate, FormularioInsumoList, FormularioInsumoJefatura, \
                FormularioInsumoAdminInterna, FormularioInsumoBodega
from . import views
from .views import ExportarExcelFormulario


app_name = 'formularioInsumos'
login_url = '/usuarios/login/'


urlpatterns = [

    # Formulario Solicitud Insumos
    path('', login_required(FormularioInsumoList.as_view(), login_url=login_url), name="index"),
    path('formularios-list/', login_required(FormularioInsumoList.as_view(), login_url=login_url), name="formularios-list"),
    #path('insumo/<int:pk>/', InsumoDetail.as_view(), name="insumo-detail"),
    path('formulario-create/', login_required(FormularioInsumoCreate.as_view(), login_url=login_url), name="formulario-create"),    
    path('formulario-jefatura/<int:pk>/', login_required(FormularioInsumoJefatura.as_view(), login_url=login_url), name="formulario-jefatura"),
    path('formulario-adminiterna/<int:pk>/', login_required(FormularioInsumoAdminInterna.as_view(), login_url=login_url), name="formulario-adminiterna"),
    path('formulario-bodega/<int:pk>/', login_required(FormularioInsumoBodega.as_view(), login_url=login_url), name="formulario-bodega"),
    path('ajax/insumos-sinstock/', login_required(views.InsumossinStock, login_url=login_url), name='ajax_insumos_sinstock'), 

    # Exportar Excel
    path('formularios-exportar/', login_required(ExportarExcelFormulario, login_url=login_url), name="formularios-exportar"), 
]

reportes/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

from .views import CierreMensualReport, CierreMensualExportarExcel, SolicitudesReport, \
                SolicitudesExportarExcel, InventarioReport, InventarioExportarExcel, GenerarComprobantePDF


app_name = 'reportes'
login_url = '/usuarios/login/'

urlpatterns = [

    ##  Cierre Mensual  ##    
    path('cierremensual-report/', login_required(CierreMensualReport.as_view(), login_url=login_url), name="cierremensual-report"),
    path('cierremensual-exportar/<int:id>', login_required(CierreMensualExportarExcel, login_url=login_url), name="cierremensual-exportar"),


    ##  Solicitudes  ##
    path('solicitudes-report/', login_required(SolicitudesReport.as_view(), login_url=login_url), name="solicitudes-report"),
    path('solicitudes-exportar/', login_required(SolicitudesExportarExcel, login_url=login_url), name="solicitudes-exportar"),


    ##  Inventario  ##
    path('inventario/', login_required(InventarioReport.as_view(), login_url=login_url), name="inventario-report"),
    path('inventario-exportar/', login_required(InventarioExportarExcel, login_url=login_url), name="inventario-exportar"),

    ##  Comprobante de Solicitud PDF    ##
    path('form-insumo/<int:id>/', login_required(GenerarComprobantePDF, login_url=login_url), name='form-insumo'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

formularioInsumos/models.py
from django.utils import  timezone
from django import template
from django.db import models
from django.conf import settings

from datetime import datetime
from departamentos.models import Departamento, Subdepartamento, Unidad
from insumos.models import Insumo
from user.models import UserProfile
from logs.models import Log


# Clase para el uso de filtros y llamadas a funciones del Modelo 
register = template.Library()



class Formulario(models.Model):
    id_formulario = models.AutoField(primary_key=True)
    folio = models.CharField(max_length=50, unique=True, verbose_name="Folio")
    id_departamento = models.ForeignKey(Departamento, on_delete=models.PROTECT, verbose_name="Departamento")
    id_sub_departamento = models.ForeignKey(Subdepartamento, on_delete=models.PROTECT, verbose_name="Sub Departamento", null=True)    
    id_unidad = models.ForeignKey(Unidad, on_delete=models.PROTECT, verbose_name="Unidad", null=True)
    fecha_creacion = models.DateField(verbose_name="Fecha Creación")
    rut_solicitante = models.CharField(max_length=50, verbose_name="Rut Solicitante")
    rut_jefe_aprobador = models.CharField(max_length=50, verbose_name="Rut Jefe Aprobador")
    rut_admin_interna = models.CharField(max_length=50, verbose_name="Rut Administración Interna")
    estado = models.BooleanField(default=True, verbose_name="Estado")   


    class Meta:
        ordering = ['-pk']


    def get_max_id(self):        
        maxId = Formulario.objects.all().order_by('-id_formulario').first()

        if (maxId is not None):
            return int(maxId.folio.split('/')[0][1:]) + 1
        else:
            return 1



    def save(self, **kwargs):
        
        if not self.id_formulario:   
            maxId = self.get_max_id()
            anio = str(datetime.now().strftime('%Y'))
            folio = "E{:06d}".format(maxId if maxId is not None else 1) + '/' + anio


            self.folio = folio
            self.hora_ingreso = datetime.now().strftime('%H:%M:%S')
            
            super(Formulario, self).save(**kwargs)
            objF = Formulario.objects.get(folio = folio)

            SHistorial = FormularioHistorial()
            SHistorial.id_folio_formulario = objF
            SHistorial.estado_formulario = settings.ESTADO_APROBACION_SOLICITUD[0][0]
            SHistorial.estado = True
            SHistorial.save()


    # @register.filter(name="get_edo_solicitud_insumo")
    # def get_edo_solicitud_insumo(self):     
    #     edo_solicitud = FormularioHistorial.objects.filter(id_folio_formulario = self.id_formulario).order_by('-pk').first()
    #     return settings.ESTADO_APROBACION_SOLICITUD[edo_solicitud.estado_formulario - 1][1]




class FormularioInsumo(models.Model):
    id_folio = models.ForeignKey(Formulario, on_delete=models.PROTECT, verbose_name="Folio")
    id_insumo = models.ForeignKey(Insumo, on_delete=models.PROTECT, verbose_name="Insumo")

    cantidad = models.IntegerField(verbose_name="Cantidad")
    cantidad_aprobada_jefatura = models.IntegerField(verbose_name="Cantidad Aprobada por Jefatura", default=0)
    cantidad_entregada = models.IntegerField(verbose_name="Cantidad Entregada", default=0)
    precio = models.FloatField(verbose_name="Precio", default=0)
    estado = models.BooleanField(default=True, verbose_name="Estado")



class FormularioHistorial(models.Model):
    id_folio_formulario = models.ForeignKey(Formulario, on_delete=models.PROTECT, verbose_name="Folio")
    fecha_hora = models.DateTimeField(default=timezone.now)
    estado_formulario = models.IntegerField(verbose_name="Estado Solicitud")
    rut_gestor = models.CharField(max_length=50, verbose_name="Rut Gestor")
    estado = models.BooleanField(default=True, verbose_name="Estado")

formularioInsumos/forms.py
from datetime import date
from django import forms
from django.forms.widgets import NumberInput
from django.forms import inlineformset_factory

from departamentos.models import Departamento, Subdepartamento, Unidad
from .models import Formulario, FormularioInsumo
from insumos.models import Insumo


class FormularioForm(forms.ModelForm):

    id_departamento = forms.ModelChoiceField(queryset = Departamento.objects.all(), label = "Departamento",
    empty_label = "Seleccione Departamento", widget = forms.Select(attrs={'class': 'form-select form-header disabled', 'readonly': 'true'}))

    id_sub_departamento = forms.ModelChoiceField(queryset = Subdepartamento.objects.all(), label = "Sub Departamento",
    empty_label = "Seleccione Sub Departamento", required=False, widget = forms.Select(attrs={'class': 'form-select form-header disabled', 'readonly': 'true'}))

    id_unidad = forms.ModelChoiceField(queryset = Unidad.objects.all(), label = "Unidad",
    empty_label = "Seleccione Unidad", required=False, widget = forms.Select(attrs={'class': 'form-select form-header disabled', 'readonly': 'true'}))

    fecha_creacion = forms.DateField(label="Fecha Creación", initial=date.today, widget = forms.DateInput(attrs={'class': 'form-control form-header disabled', 'readonly': 'true'}))

    rut_solicitante = forms.CharField(label='', widget = forms.HiddenInput(attrs={'class':'d-none form-hidden'}), required=False)
    rut_jefe_aprobador = forms.CharField(label='', widget = forms.HiddenInput(attrs={'class':'d-none form-hidden'}), required=False)
    rut_admin_interna = forms.CharField(label='', widget = forms.HiddenInput(attrs={'class':'d-none form-hidden'}), required=False)
    estado_solicitud = forms.CharField(label='', widget = forms.HiddenInput(attrs={'class':'d-none form-hidden'}), required=False)


    class Meta:
        model = Formulario
        fields = ('fecha_creacion', 'id_departamento', 'id_sub_departamento', 'id_unidad', 'rut_solicitante', 'rut_jefe_aprobador', 'rut_admin_interna', 'estado_solicitud')
        
        widgets = {
            'folio': forms.TextInput(attrs={'class': 'form-control form-header', 'disabled': 'disabled'}),        
            'estado': forms.CheckboxInput(attrs={'class': 'form-check-input', 'disabled': 'disabled'}),
        }



class FormularioInsumoForm(forms.ModelForm):

    id_insumo = forms.ModelChoiceField(queryset = Insumo.objects.all(), label = "Insumo", 
    empty_label = "Seleccione Insumo", widget = forms.Select(attrs={'class': 'form-select select2 col-md-2', 'required': 'true'}))

    class Meta:
        model = FormularioInsumo
        fields = ('id_insumo', 'cantidad')

        widgets = {
            'cantidad': forms.NumberInput(attrs={'class': 'form-control col-md-2', 'required': 'true', 'min': 1}),
        }




class FormularioInsumoJefaturaForm(forms.ModelForm):

    id_insumo = forms.ModelChoiceField(queryset = Insumo.objects.all(), label = "Insumo", 
    empty_label = "Seleccione Insumo", widget = forms.Select(attrs={'class': 'form-select disabled col-md-2', 'required': 'true'}))

    precio = forms.FloatField(widget = forms.NumberInput(attrs={'class': 'form-control disabled', 'readonly': 'true'}))

    class Meta:
        model = FormularioInsumo
        fields = ('id_insumo', 'cantidad', 'precio', 'cantidad_aprobada_jefatura')

        widgets = {
            'cantidad': forms.NumberInput(attrs={'class': 'form-control disabled col-md-2', 'required': 'true'}),
            'cantidad_aprobada_jefatura': forms.NumberInput(attrs={'class': 'form-control col-md-2', 'required': 'true'}),
        }




class FormularioInsumoAdminInternaForm(forms.ModelForm):

    id_insumo = forms.ModelChoiceField(queryset = Insumo.objects.all(), label = "Insumo", 
    empty_label = "Seleccione Insumo", widget = forms.Select(attrs={'class': 'form-select disabled col-md-2', 'required': 'true'}))

    precio = forms.FloatField(widget = forms.NumberInput(attrs={'class': 'form-control disabled', 'readonly': 'true'}))


    class Meta:
        model = FormularioInsumo
        fields = ('id_insumo', 'cantidad', 'precio', 'cantidad_aprobada_jefatura', 'cantidad_entregada')

        widgets = {
            'cantidad': forms.NumberInput(attrs={'class': 'form-control disabled col-md-2'}),
            'cantidad_aprobada_jefatura': forms.NumberInput(attrs={'class': 'form-control col-md-2 disabled'}),
            'cantidad_entregada': forms.NumberInput(attrs={'class': 'form-control col-md-2'}),
        }




class FormularioInsumoBodegaForm(forms.ModelForm):

    id_insumo = forms.ModelChoiceField(queryset = Insumo.objects.all(), label = "Insumo", 
    empty_label = "Seleccione Insumo", widget = forms.Select(attrs={'class': 'form-select disabled col-md-2', 'required': 'true'}))

    precio = forms.FloatField(widget = forms.NumberInput(attrs={'class': 'form-control disabled'}))


    class Meta:
        model = FormularioInsumo
        fields = ('id_insumo', 'cantidad', 'precio', 'cantidad_entregada')

        widgets = {
            'cantidad': forms.NumberInput(attrs={'class': 'form-control disabled col-md-2'}),
            'cantidad_entregada': forms.NumberInput(attrs={'class': 'form-control col-md-2'}),
        }




FormularioInsumoFormSet = inlineformset_factory(
    Formulario, FormularioInsumo, form=FormularioInsumoForm,
    extra=1, can_delete=False
)


FormularioInsumoJefaturaFormSet = inlineformset_factory(
    Formulario, FormularioInsumo, form=FormularioInsumoJefaturaForm,
    extra=0, can_delete=False
)


FormularioInsumoAdminInternaFormSet = inlineformset_factory(
    Formulario, FormularioInsumo, form=FormularioInsumoAdminInternaForm,
    extra=0, can_delete=False
)


FormularioInsumoBodegaFormSet = inlineformset_factory(
    Formulario, FormularioInsumo, form=FormularioInsumoBodegaForm,
    extra=0, can_delete=False
)

formularioInsumos/templates/formularioInsumos/formulario_form.html
{% extends 'insumos/index.html' %}

{% block content %}
    
      <div class="pagetitle">
        <h1>Insumos</h1>
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'formularios:index' %}">Inicio</a></li>
            <li class="breadcrumb-item">Formulario Solicitud Insumos</li>
          </ol>
        </nav>
      </div><!-- End Page Title -->
  
      <section class="section">
        <div class="row">
          <div class="col-lg-12">
  
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Formulario Solicitud Insumos</h5>
  
                <!-- Create/Update FormularioInsumos -->
                <form id="formFormulario" enctype="multipart/form-data" method="post" autocomplete="off">
                    {% csrf_token %}

                    {% for field in form %}

                        {% if 'form-header' in field.field.widget.attrs.class %}
                        <div class="form-group mb-2">
                            <label>{{field.label}}</label>
                            {% if field.field.required %}
                                <span class="required"></span>
                            {% endif %}
                        
                            {{field}}
                            {% if field.help_text %}
                                <small style="color: grey">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}

                    {% endfor %}

                        <!-- inline form for detalle Fsctura Compra start -->

                        <!-- EXPLAINING with named_formsets.variants as formset -->
                        <!-- Note: named_formsets is used in get_context_data function in views.py -->
                        <!-- Note: here variants is our CompraInsumoFormSet name, used in get_named_formsets function in views.py -->

                        {% with named_formsets.detallesolicitud as formset %}
                            {{ formset.management_form }}

                            <script type="text/html" id="detallesolicitud-template">
                                <tr id="detallesolicitud-__prefix__" class= hide_all>
                                    {% for fields in formset.empty_form.hidden_fields %}
                                        {{ fields }}
                                    {% endfor %}
                                
                                    {% for fields in formset.empty_form.visible_fields %}
                                        <td>{{fields}}</td>
                                    {% endfor %}

                                    <td><button type="button" class="btn btn-sm btn-warning delete-item-solic">Eliminar</button></td>
                                </tr>
                            </script>


                            <div class="d-flex mt-3">
                                <div class="col-6 flex-fill">
                                    <h5 class="card-title col-6">Detalle Insumos</h5>
                                </div>
                            
                                <div class="col-6 flex-fill text-end mt-3">
                                    <a href="#" id="add-detallesolicitud-button" class="btn btn-primary add-detallesolicitud">Agregar Insumo</a>
                                </div>
                            </div>


                                <table class="table table-striped">
                                    <thead class="text-center">
                                        <th scope="col" class="required">Insumo </th>
                                        <th scope="col" class="required">Cantidad </th>
                                        <th scope="col" class="d-none"></th>
                                    </thead>
                                    <tbody id="item-detallesolicitud">

                                        {% for formss in formset %}
                                            {{ formss.management_form }}
                                            <tr id="detallesolicitud-{{ forloop.counter0 }}" class= hide_all> 
                                                {{ formss.id }}
                                                {% for field in formss.visible_fields %}
                                                    <td>
                                                        {{ field }}
                                                        {% for error in field.errors %}
                                                            <span style="color: red">{{ error }}</span>
                                                        {% endfor %}
                                                    </td>
                                                {% endfor %}

                                              {% if formss.instance.pk %}
                                                    <td>
                                                        
                                                        <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#exampleModal{{formss.instance.pk}}" onclick="$('#exampleModal{{formss.instance.pk}}').modal('show')">
                                                            Eliminar
                                                        </button>
                                                        < ! -- Modal -- 
                                                        <div class="modal fade" id="exampleModal{{formss.instance.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{formss.instance.pk}}" aria-hidden="true">
                                                            <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                <h5 class="modal-title" id="exampleModalLabel{{formss.instance.pk}}"¿Desea eliminar el registro?</h5>
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <a href="{% url 'formularios:index' formss.instance.pk %}" type="button" class="btn btn-primary">Eliminar</a>
                                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                                </div>
                                                            </div>
                                                            </div>
                                                        </div>
                                                    </td>
                                                
                                                {% else %} 
                                                    <td><button type="button" class="btn btn-sm btn-warning delete-item-solic d-none">Eliminar</button></td>
                                                {% endif %}

                                            </tr>
                                        {% endfor %}

                                    </tbody>
                                </table>                      
                            
                            {% endwith %}
                            <!-- inline form for Factura Compra end -->

                            {% for field in form %}

                              {% if 'form-hidden' in field.field.widget.attrs.class %}                              
                                  {{field}}
                              {% endif %}

                            {% endfor %}
                    <br><br>

                    <div class="col-12 text-end">
                      <input type="submit" class="btn btn-primary" value="Guardar">
                      <a href="{% url 'formularios:index' %}" class="btn btn-outline-primary">Cancelar</a>
                    </div>

                </form>
                <!-- End Formulario FormularioInsumos -->
  
              </div>
            </div>
  
          </div>
  
          <div class="col-lg-5"></div>
          
        </div>
      </section>
  
{% endblock %}


{% block jscript %}
<script>
  $(function() {

    $(window).on("load",function() {
      // Eliminar fila extra en detalle insumo
      if ( $("#item-detallesolicitud tr").length > 1) {
          $("#item-detallesolicitud tr:last").remove();
      }

      insumos_sinstock();
    });


    $('.disabled').on('mousedown', function(e) {
      e.preventDefault();
    });

    $('.select2').on('click', function(e) {
      $("li[class*='option--disabled']").attr('style', 'background-color:#f8d7da !important');
    });

    $('.add-detallesolicitud').click(function(ev) {
      ev.preventDefault();
      var count = $('#item-detallesolicitud').children().length;
      var tmplMarkup = $('#detallesolicitud-template').html();
      var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);        
      $('#item-detallesolicitud').append(compiledTmpl);
      // update form count
      $('#id_detallesolicitud-TOTAL_FORMS').attr('value', count+1);

      insumos_sinstock();

      if ( $("#item-detallesolicitud tr").length > 1) {
          $(".delete-item-solic").removeClass("d-none");
      } else {
          $(".delete-item-solic").addClass("d-block");
      }

  });


  function insumos_sinstock() {
    let url = "{% url 'formularioInsumos:ajax_insumos_sinstock' %}"

    $.ajax({                                      
        url: url,                                                 
        success: function (resp) {              

          if (resp != null)
              $.each(resp.data, function (key, value) {                
                $("select[name*='id_insumo'] option[value='" + value + "']").prop('disabled','disabled').append("&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; * Sin Stock *");
              });

        }
    });
  } 


  $(document).on("click",'.delete-item-solic',function(){
    if ( $("#item-detallesolicitud tr").length > 1) {
        $(this).closest("tr").remove();
    }

    if ( $("#item-detallesolicitud tr").length == 1) {
        $(".delete-item-solic").addClass("d-none").removeClass("d-block");
    } 
  });


    // Dropdown Departamento
/*    $("#id_id_departamento").change(function () {
      var url = $("#formFormulario").attr("data-subdptos-url");   // obtener la url de la vista 'loadSubDepartamentos'
      var DptoId = $(this).val();                                 // obtener id del Departamento

      $.ajax({                                      
        url: url,                                                 // request url (localhost:8000/formularios/ajax/load-subdptos/)
        data: {
          'dpto': DptoId                                          // id del Departamento como parámetro 
        },
        success: function (data) {                    
          $("#id_id_sub_departamento").html(data);                // poblar dropdown subdepartamento
        }
      });
    });

    // Dropdown SubDepartamento
    $("#id_id_sub_departamento").change(function () {
      var url = $("#formFormulario").attr("data-unidades-url");   // obtener la url de la vista 'loadSubDepartamentos'
      var SubDptoId = $(this).val();                              // obtener id del SubDepartamento

      $.ajax({                                                
        url: url,                                                 // request url (localhost:8000/formularios/ajax/load-unidades/)
        data: {
          'subdpto': SubDptoId                                    // id de Subdepartamento como parámetro 
        },
        success: function (data) {                            
          $("#id_id_unidad").html(data);                          // poblar dropdown Unidad
        }
      });
    });*/

  });
</script>
{% endblock %}

formularioInsumos/templates/formularioInsumos/subdepartamentos_list_options.html
    <option value="">Seleccione Sub Departamento</option>
{% for subdpto in subdepartamentos %}
    <option value="{{ subdpto.id }}">{{ subdpto.nombre_sub_dpto }}</option>
{% endfor %}

formularioInsumos/templates/formularioInsumos/unidades_list_options.html
    <option value="">Seleccione Unidad</option>
{% for unid in unidades %}
    <option value="{{ unid.id }}">{{ unid.nombre_unidad }}</option>
{% endfor %}