core/urls.py
from tkinter.font import names
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('insumos.urls', namespace="insumos")),
    path('departamentos/', include('departamentos.urls', namespace="departamentos")),
    path('usuarios/', include('user.urls', namespace="usuarios")),
    path('formularios/', include('formularioInsumos.urls', namespace="formularios")),
    path('cargos/', include('cargos.urls', namespace="cargos")),
    path('formulariosr/', include('formularioSR.urls', namespace="formulariosr")),
    path('proveedores/', include('proveedores.urls', namespace="proveedores")),
    path('compras/', include('compras.urls', namespace="compras")),
    path('presupuesto/', include('presupuesto.urls', namespace="presupuestos")),
    path('cierremensual/', include('cierreMensual.urls', namespace="cierremensual")),
    path('configuraciones/', include('configuraciones.urls', namespace="configuraciones")),
    path('logs/', include('logs.urls', namespace="logs")),
    path('inventario/', include('inventario.urls', namespace="inventario")),
    path('reportes/', include('reportes.urls', namespace="reportes")),
]


handler404 = 'user.views.error_404'
handler403 = 'user.views.error_403'

departamentos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import DptoListView, DptoCreateView, DptoUpdateView, \
                  SubDptoListView, SubDptoCreateView, SubDptoUpdateView, \
                  UnidadListView, UnidadCreateView, UnidadUpdateView, \
                  ExportarExcelDptos, ExportarExcelSubDptos, ExportarExcelUnidades 

app_name = 'departamentos'
login_url = '/usuarios/login/'


urlpatterns = [
   
   #Departamentos
   path('', login_required(DptoListView.as_view(), login_url=login_url), name='dptos-list'),
   path('dptos-list/', login_required(DptoListView.as_view(), login_url=login_url), name='dptos-list'),
   path('dpto-create/', login_required(DptoCreateView.as_view(), login_url=login_url), name='dpto-create'),
   path('dpto-update/<int:pk>/', login_required(DptoUpdateView.as_view(), login_url=login_url), name='dpto-update'),


   #SubDepartamentos
   path('subdptos-list/', login_required(SubDptoListView.as_view(), login_url=login_url), name='subdptos-list'),
   path('subdpto-create/', login_required(SubDptoCreateView.as_view(), login_url=login_url), name='subdpto-create'),
   path('subdpto-update/<int:pk>/', login_required(SubDptoUpdateView.as_view(), login_url=login_url), name='subdpto-update'),


   #Unidadeds   
   path('unidades-list/', login_required(UnidadListView.as_view(), login_url=login_url), name='unidades-list'),
   path('unidad-create/', login_required(UnidadCreateView.as_view(), login_url=login_url), name='unidad-create'),
   path('unidad-update/<int:pk>/', login_required(UnidadUpdateView.as_view(), login_url=login_url), name='unidad-update'),


   # Exportar Excel
   path('departamentos-exportar/', login_required(ExportarExcelDptos, login_url=login_url), name="departamentos-exportar"),
   path('subdepartamentos-exportar/', login_required(ExportarExcelSubDptos, login_url=login_url), name="subdepartamentos-exportar"),
   path('unidades-exportar/', login_required(ExportarExcelUnidades, login_url=login_url), name="unidades-exportar"),
]

insumos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import CategoriaList, CategoriaCreate, CategoriaDetail, CategoriaUpdate, CategoriaDelete, \
                InsumoList, InsumoDetail, InsumoCreate, InsumoUpdate, InsumoDelete, UnidadMedidaCreate, \
                UnidadMedidaDelete, UnidadMedidaDetail, UnidadMedidaList, UnidadMedidaUpdate, ExportarExcel, \
                ExportarExcelUnidadMedida, ExportarExcelCategorias


app_name = 'insumos'
login_url = '/usuarios/login/'


urlpatterns = [
    # Insumos
    path('', login_required(InsumoList.as_view(), login_url=login_url), name="index"),
    path('insumos-list/', login_required(InsumoList.as_view(), login_url=login_url), name="insumos-list"),
    path('insumo/<int:pk>/', login_required(InsumoDetail.as_view(), login_url=login_url), name="insumo-detail"),
    path('insumo-create/', login_required(InsumoCreate.as_view(), login_url=login_url), name="insumo-create"),
    path('insumo-update/<int:pk>/', login_required(InsumoUpdate.as_view(), login_url=login_url), name="insumo-update"),
    path('insumo-delete/<int:pk>/', login_required(InsumoDelete.as_view(), login_url=login_url), name="insumo-delete"),


    # Categorías
    path('categorias-list/', login_required(CategoriaList.as_view(), login_url=login_url), name="categorias-list"),
    path('categoria/<int:pk>/', login_required(CategoriaDetail.as_view(), login_url=login_url), name="categoria-detail"),
    path('categoria-create/', login_required(CategoriaCreate.as_view(), login_url=login_url), name="categoria-create"),
    path('categoria-update/<int:pk>/', login_required(CategoriaUpdate.as_view(), login_url=login_url), name="categoria-update"),
    path('categoria-delete/<int:pk>/', login_required(CategoriaDelete.as_view(), login_url=login_url), name="categoria-delete"),


    # Unidad de Medidas
    path('unidadmedidas-list/', login_required(UnidadMedidaList.as_view(), login_url=login_url), name="unidadmedidas-list"),
    path('unidadmedida/<int:pk>/', login_required(UnidadMedidaDetail.as_view(), login_url=login_url), name="unidadmedida-detail"),
    path('unidadmedida-create/', login_required(UnidadMedidaCreate.as_view(), login_url=login_url), name="unidadmedida-create"),
    path('unidadmedida-update/<int:pk>/', login_required(UnidadMedidaUpdate.as_view(), login_url=login_url), name="unidadmedida-update"),
    path('unidadmedida-delete/<int:pk>/', login_required(UnidadMedidaDelete.as_view(), login_url=login_url), name="unidadmedida-delete"),


    # Exportar Excel
    path('insumos-exportar/', login_required(ExportarExcel, login_url=login_url), name="insumos-exportar"),
    path('unidadmedida-exportar/', login_required(ExportarExcelUnidadMedida, login_url=login_url), name="unidadmedida-exportar"),
    path('categorias-exportar/', login_required(ExportarExcelCategorias, login_url=login_url), name="categorias-exportar"),
]

user/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import home, RegisterView, CustomLoginView
from .views import UsuariosList, PerfilList, PerfilCreate, PerfilUpdate, PerfilDelete, \
    GestionPerfilUpdate, LogoutView, ExportarExcelFuncionarios, MainView
from . import views


app_name = 'user'
login_url = '/usuarios/login/'


urlpatterns = [  

    #Registro/Login
    #path('',home.as_view(),name='home'),
    path('registro/', RegisterView.as_view(), name='registro'),
    path('usuarios-list/', login_required(UsuariosList.as_view(), login_url=login_url), name="usuarios-list"),
    path('login/', CustomLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('main/', MainView.as_view(), name="main"),


    #Perfiles
    path('perfiles-list/', login_required(PerfilList.as_view(), login_url=login_url), name="perfiles-list"),
    path('perfil-create/', login_required(PerfilCreate.as_view(), login_url=login_url), name="perfil-create"),
    path('perfil-update/<int:pk>/', login_required(PerfilUpdate.as_view(), login_url=login_url), name="perfil-update"),
    path('perfil-gestion/<int:pk>/', login_required(GestionPerfilUpdate.as_view(), login_url=login_url), name="perfil-gestion"),
    path('perfil-delete/<int:pk>/', login_required(PerfilDelete.as_view(), login_url=login_url), name="perfil-delete"),
    path('ajax/load-subdptos/', views.loadSubDepartamentos, name='ajax_load_subdptos'),
    path('ajax/load-unidades/', views.loadUnidades, name='ajax_load_unidades'),


    # Exportar Excel
    path('funcionarios-exportar/', login_required(ExportarExcelFuncionarios, login_url=login_url), name="funcionarios-exportar"), 
]

user/models.py
import email
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django import template
from django.conf import settings

from departamentos.models import Departamento, Subdepartamento, Unidad
from cargos.models import Cargo


# Clase para el uso de filtros y llamadas a funciones del Modelo 
register = template.Library()



class Perfil(models.Model):
    nombre_perfil = models.CharField(max_length=50, verbose_name="Nombre Perfil")
    estado = models.BooleanField(default=True, verbose_name="Estado")


    class Meta:
        ordering = ['id']


    def __str__(self):
        return self.nombre_perfil


    def get_default_Perfil(self):
        return self.objects.get(id=2).id


    @register.filter(name="get_estado_perfil")
    def get_estado_perfil(self):     
        edo_perfil = Perfil.objects.filter(id = self.id)
        return settings.ESTADO[0][edo_perfil[0].estado]



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="userprofile", verbose_name="Usuario")
    rut = models.CharField(max_length=20, verbose_name="Rut", unique=True)   
    anexo = models.IntegerField(default=0, blank=True, null=True, verbose_name="Anexo")
    estado = models.BooleanField(default=True, verbose_name="Estado")
    id_perfil = models.ForeignKey(Perfil, on_delete=models.PROTECT, verbose_name="Perfil", default=Perfil.get_default_Perfil(Perfil))


    class Meta:
        ordering = ['id']


    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name


    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)


    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()


    @register.filter(name="get_estado_user")
    def get_estado_user(self):     
        edo_user = UserProfile.objects.filter(id = self.id)
        return settings.ESTADO[0][edo_user[0].estado]


    @register.filter(name="get_cargo_user")
    def get_cargo_user(self):     
        cargo = UserCargo.objects.filter(id_usuario = self.user).values_list('id_cargo__nombre_cargo')
        return cargo[0][0] if cargo else ''


    # def login_user(request):

    #     if request.method == "POST":
    #         username = request.POST.get('username')
    #         password = request.POST.get('password')
    #         user = authenticate(username=username, password=password)
    
    #         if user is not None:
    #             if user.is_active:
    #                 login(request, user)
    
    #                 return HttpResponseRedirect('/user/login.html')
    #             else:
    #                 return HttpResponse("Inactive user.")
    #         else:
    #             return HttpResponseRedirect(settings.LOGIN_URL)
    
    #     return render(request, "index.html")



class UserDepartamento(models.Model):
    id_departamento = models.ForeignKey(Departamento, on_delete=models.PROTECT, verbose_name="Departamento", related_name="usuario_dpto", blank=True, null=True)
    id_sub_departamento = models.ForeignKey(Subdepartamento, on_delete=models.PROTECT, verbose_name="Sub Departamento", related_name="usuario_subdpto", blank=True, null=True)
    id_unidad = models.ForeignKey(Unidad, on_delete=models.PROTECT, verbose_name="Unidad", related_name="usuario_unidad", blank=True, null=True)
    id_usuario = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="usuario_id_dpto", related_name="usuario_id_dpto")



class UserCargo(models.Model):
    id_cargo = models.ForeignKey(Cargo, on_delete=models.PROTECT, verbose_name="Cargo", related_name="cargo", default=1)
    id_usuario = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Usuario", related_name="usuario_cargo")
    fecha_activacion = models.DateField(verbose_name="Fecha Activación", null=True, blank=True)
    fecha_desactivacion = models.DateField(verbose_name="Fecha Desactivación", null=True, blank=True)
    estado = models.BooleanField(default=True, verbose_name="Estado")

user/forms.py
from http.client import REQUEST_ENTITY_TOO_LARGE
from tabnanny import verbose
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from departamentos.models import Departamento, Subdepartamento, Unidad
from cargos.models import Cargo
from .models import Perfil, UserCargo, UserDepartamento, UserProfile


class RegisterForm(UserCreationForm):

    rut = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={'class': 'form-control', }))
    first_name = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'class': 'form-control',}), label="Nombre")
    last_name = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'class': 'form-control', }), label="Apellido")
    username = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'class': 'form-control', }), label="Usuario")
    email = forms.EmailField(required=True,widget=forms.TextInput(attrs={'class': 'form-control',}), label="Email")
    password1 = forms.CharField(max_length=50,required=True,widget=forms.PasswordInput(attrs={'class': 'form-control','data-toggle': 'password','id': 'password',}), label="Password")
    password2 = forms.CharField(max_length=50,required=True,widget=forms.PasswordInput(attrs={'class': 'form-control','data-toggle': 'password','id': 'password',}), label="Confirmar Password")
    anexo = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'class': 'form-control',}), label="Anexo")


    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username','email', 'password1', 'password2', 'rut', 'anexo')



class LoginForm(forms.ModelForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class':'form-control', }), label="Usuario")
    password = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput(attrs={'class':'form-control','data-toggle':'password','id':'password',}), label="Password")

    class Meta:
        model = User
        fields = ('username', 'password')
        excludes = ('first_name', 'last_name', 'email')



# Edición y Asignación de Perfiles, Departamentos, Cargos a Usuarios

class UsuarioForm(forms.ModelForm):

    first_name = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'class': 'form-control',}), label="Nombre")
    last_name = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'class': 'form-control', }), label="Apellido")
    username = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'class': 'form-control disabled', }), label="Usuario")
    email = forms.EmailField(required=True,widget=forms.TextInput(attrs={'class': 'form-control',}), label="Email")

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username','email')
        excludes = ('password1', 'password2')



class PerfilForm(forms.ModelForm):

    class Meta:
        model = Perfil
        fields = ('nombre_perfil', 'estado')

        widgets = {
            'nombre_perfil': forms.TextInput(attrs={'class': 'form-control'}),
            'estado': forms.CheckboxInput(attrs={'class': 'form-check-input'})
        }



class UserProfileForm(forms.ModelForm):

    rut = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={'class': 'form-control disabled'}))
    anexo = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'class': 'form-control',}), label="Anexo")
    id_perfil = forms.ModelChoiceField(queryset=Perfil.objects.all(), empty_label="Seleccione Perfil de Usuario", label="Perfil Usuario", widget = forms.Select(attrs={'class': 'form-select'}))

    class Meta:
        model = UserProfile
        fields = ('rut', 'anexo', 'id_perfil')



class UserDepartamentoForm(forms.ModelForm):

    id_departamento = forms.ModelChoiceField(queryset=Departamento.objects.all(), empty_label="Seleccione Departamento", label="Departamento", widget = forms.Select(attrs={'class': 'form-select', 'id':'id_user_departamento'}))
    id_sub_departamento = forms.ModelChoiceField(queryset=Subdepartamento.objects.all(), empty_label="Seleccione Subdepartamento", required=False, label="Sub Departamento", widget = forms.Select(attrs={'class': 'form-select', 'id':'id_user_subdepartamento'}))
    id_unidad = forms.ModelChoiceField(queryset=Unidad.objects.all(), empty_label="Seleccione Unidad", label="Unidad", required=False, widget = forms.Select(attrs={'class': 'form-select', 'id':'id_user_unidad'}))
    
    class Meta:
        model = UserDepartamento
        fields = ('id_departamento', 'id_sub_departamento', 'id_unidad')



class UserCargoForm(forms.ModelForm):

    id_cargo = forms.ModelChoiceField(queryset=Cargo.objects.all(), empty_label="Seleccione Cargo", label="Cargo", widget=forms.Select(attrs={'class': 'form-select'}))

    class Meta:
        model = UserCargo
        fields = ('id_cargo',)

user/templates/user/_base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title%} {% endblock title %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />

    {% block style %} {% endblock style %}
  </head>

  <header class="main-head">
    <div class="container">
      <nav class="navbar navbar-expand-sm bg-light navbar-light">
      <div class="container-fluid">
        <!-- Links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'usuarios:home' %}">Inicio</a>
          </li>
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li> {% endcomment %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'usuarios:registro' %}">Registro</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'departamentos:dptos-list' %}">Lista Departamentos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'departamentos:subdptos-list' %}">Lista Sub-Departamentos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'departamentos:unidades-list' %}">Lista Unidad</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'departamentos:dpto-create' %}">Crear Departamento</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'departamentos:subdpto-create' %}">Crear Sub Departamento</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'departamentos:unidad-create' %}">Crear Unidad</a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
  </header>
  <body>
    <div class="container">{% block content %} {% endblock content %}</div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

user/templates/user/_home.html
{% extends 'user/base.html' %}



{% block content %}

{% endblock content %}

user/templates/user/_register.html
{% extends 'social/layout.html' %}

{% block content %}

<form class="form" method="post">
	{% csrf_token %}
	{{ form.as_p }}

	<button type="submit" id="submit">Registrarse</button>
</form>

{% endblock %}

user/templates/user/perfil_confirm_delete.html
{% extends 'insumos/index.html' %}

{% block content %}

    <form id="formDeletePerfil" method="post">{% csrf_token %}
        <p>¿Desea eliminar el perfil "{{ object }}"?</p>
        {{ form }}
        <input type="submit" class="btn btn-primary" value="Confirmar">
        <a href="{% url 'user:perfiles-list' %}" class="btn btn-outline-primary">Cancelar</a>
    </form>

{% endblock %}

user/templates/user/perfil_gestion.html
{% extends 'insumos/index.html' %}

{% block content %}
    
    <div class="pagetitle">
        <h1>Gestión de Usuarios</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Inicio</a></li>
                <li class="breadcrumb-item">Perfil</li>
            </ol>
        </nav>
    </div>

    <section class="section">
        <div class="row">
            <div class="col-lg-8">

            <div class="card">
                <div class="card-body">
                <h5 class="card-title">Gestión Perfiles de Usuario</h5>

                <form id="formGestionPerfil" method="post" data-subdptos-url="{% url 'user:ajax_load_subdptos' %}" 
                data-unidades-url="{% url 'user:ajax_load_unidades' %}" action="" novalidate autocomplete="off">
                    {% csrf_token %}
                    {{form.as_p}}

                    {% for formset in inlines %}
                        {{ formset.as_p }}
                    {% endfor %} 

                    <div class="col-12 text-end">
                        <input type="submit" class="btn btn-primary" value="Guardar">
                        <a href="{% url 'user:usuarios-list' %}" class="btn btn-outline-primary">Cancelar</a>
                    </div>
                </form>

            </div>
        </div>

    </div>

    <div class="col-lg-5"></div>

    </div>
</section>

{% endblock %}

{% block js %}
<script>
$(function() {

    // Dropdown Departamento
    $("#id_user_departamento").change(function () {
      var url = $("#formGestionPerfil").attr("data-subdptos-url");          // obtener la url de la vista 'loadSubDepartamentos'
      var DptoId = $(this).val();                                           // obtener id del Departamento

        $.ajax({                                      
            url: url,                                                       // request url (localhost:8000/formularios/ajax/load-subdptos/)
            data: {
              'dpto': DptoId                                                // id del Departamento como parámetro 
            },
            success: function (data) {                    
              $("#id_user_subdepartamento").html(data);                     // poblar dropdown subdepartamento
            }
        });
    });

    // Dropdown SubDepartamento
    $("#id_user_subdepartamento").change(function () {
      var url = $("#formGestionPerfil").attr("data-unidades-url");          // obtener la url de la vista 'loadSubDepartamentos'
      var SubDptoId = $(this).val();                                        // obtener id del SubDepartamento

        $.ajax({                                                
            url: url,                                                       // request url (localhost:8000/formularios/ajax/load-unidades/)
            data: {
              'subdpto': SubDptoId                                          // id de Subdepartamento como parámetro 
            },
            success: function (data) {                            
              $("#id_user_unidad").html(data);                              // poblar dropdown Unidad
            }
        });
    });

});
</script>
{% endblock %}

user/templates/user/perfil_list.html
{% extends 'insumos/index.html' %}

{% block content %}
    
    <div class="pagetitle">
        <h1>Perfiles</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'user:perfiles-list' %}">Inicio</a></li>
                <li class="breadcrumb-item">Perfiles</li>
                <li class="breadcrumb-item active">Listado</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <div class="col-12 mb-3">
        {% include 'insumos/searchbar.html' with urllist='user:perfiles-list' urlcreate='user:perfil-create' btnnombre='Agregar Perfil' %}
    </div>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Listado de Perfiles</h5>

        {% if perfiles %}
        <table class="table table-striped table-bordered">
            <thead class="text-center">
                <tr>
                    <th scope="col">Id Perfil</th>
                    <th scope="col">Nombre Perfil</th>
                    <th scope="col">Estado</th>
                    <th scope="col" colspan="2"></th>
                </tr>
            </thead>
            <tbody class="text-center">
                {% for perfil in perfiles %}
                <tr>
                    <td>{{ perfil.id }}</td>
                    <td class="text-start">{{ perfil.nombre_perfil }}</td>
                    <td>{{ perfil.get_estado_perfil }}</td>
                    <td class="text-center">
                        <a href="{% url 'user:perfil-update' perfil.id %}" data-toggle="tooltip" title="Editar" class="me-2"><i class="bi bi-pencil-fill"></i></a>
                        <a href="{% url 'user:perfil-delete' perfil.id %}" data-toggle="tooltip" title="Eliminar" class="ms-2"><i class="bi bi-trash3-fill d-none"></i></a>
                    </td>
                </tr>                
                {% endfor %}
            </tbody>
        </table>


        <div class="col-12 mb-3">
            {% include 'insumos/pagination.html'%}
        </div>


        {% else %}          
            <h3 class="text-center">No se encontraron Perfiles</h3>        
        {% endif %}
        </div>
    </div>

{% endblock %}

user/templates/user/usuarios_list.html
{% extends 'insumos/index.html' %}

{% block content %}
    
    <div class="pagetitle">
        <h1>Usuarios</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'insumos:categorias-list' %}">Inicio</a></li>
                <li class="breadcrumb-item">Usuarios</li>
                <li class="breadcrumb-item active">Listado</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <div class="col-12 mb-3">
        {% include 'insumos/searchbar.html' with urllist='user:usuarios-list' urlcreate='user:funcionarios-exportar' btnnombre='Exportar a Excel' %}
    </div>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Listado de Usuarios</h5>


        {% if userprofiles %}
            <table class="table table-striped table-bordered">
            <thead class="text-center">
                <tr>
                    <th scope="col">Rut</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Nombre de Usuario</th>
                    <th scope="col">Email</th>
                    <th scope="col">Perfil</th>
                    <th scope="col">Anexo</th>
                    <th scope="col">Cargo</th>
                    <th scope="col">Estado</th>
                    <th scope="col" colspan="2"></th>
                </tr>
            </thead>
            <tbody class="text-center">
                {% for usuperf in userprofiles %}
                <tr>
                    <td>{{ usuperf.rut }}</td>
                    <td>{{ usuperf.user.first_name }}</td>
                    <td>{{ usuperf.user.last_name }}</td>
                    <td>{{ usuperf.user.username }}</td>
                    <td>{{ usuperf.user.email }}</td>
                    <td>{{ usuperf.id_perfil }}</td>
                    <td>{{ usuperf.anexo|safe }}</td>
                    <td>{{ usuperf.get_cargo_user }}</td>
                    <td>{{ usuperf.get_estado_user }}</td>
                    <td colspan="" class="text-center">
                        <a href="{% url 'user:perfil-gestion' usuperf.id %}" data-toggle="tooltip" title="Editar" class="me-2"><i class="bi bi-pencil-fill"></i></a>
                        <!--<a href="{  % url 'insumos:categoria-delete' categoria.id %  }" class="ms-1">Eliminar</a>-->
                    </td>
                </tr>                
                {% endfor %}
            </tbody>
            </table>


            <div class="col-12 mb-3">
                {% include 'insumos/pagination.html'%}
            </div>


        {% else %}          
            <h3 class="text-center">No se encontraron usuarios</h3>        
        {% endif %}
        </div>
    </div>

{% endblock %}