core/urls.py
from tkinter.font import names
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('insumos.urls', namespace="insumos")),
    path('departamentos/', include('departamentos.urls', namespace="departamentos")),
    path('usuarios/', include('user.urls', namespace="usuarios")),
    path('formularios/', include('formularioInsumos.urls', namespace="formularios")),
    path('cargos/', include('cargos.urls', namespace="cargos")),
    path('formulariosr/', include('formularioSR.urls', namespace="formulariosr")),
    path('proveedores/', include('proveedores.urls', namespace="proveedores")),
    path('compras/', include('compras.urls', namespace="compras")),
    path('presupuesto/', include('presupuesto.urls', namespace="presupuestos")),
    path('cierremensual/', include('cierreMensual.urls', namespace="cierremensual")),
    path('configuraciones/', include('configuraciones.urls', namespace="configuraciones")),
    path('logs/', include('logs.urls', namespace="logs")),
    path('inventario/', include('inventario.urls', namespace="inventario")),
    path('reportes/', include('reportes.urls', namespace="reportes")),
]


handler404 = 'user.views.error_404'
handler403 = 'user.views.error_403'

presupuesto/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import  PresupuestoCategoriaList, PresupuestoCategoriaCreate, PresupuestoCategoriaUpdate, \
                    AsignacionPresupuesto, AsignacionPresupuestoUpdate, \
                    ExportarExcelCtasPresupuestarias, ExportarExcelAsignacionPresupuesto
from . import views


app_name = 'presupuesto'
login_url = '/usuarios/login/'


urlpatterns = [
    
    # Cuenta Presupuestaria
    path('', login_required(PresupuestoCategoriaList.as_view(), login_url=login_url), name="index"),
    path('cuentas-list/', login_required(PresupuestoCategoriaList.as_view(), login_url=login_url), name="cuentas-list"),
    path('cuenta-create/', login_required(PresupuestoCategoriaCreate.as_view(), login_url=login_url), name="cuenta-create"),
    path('cuenta-update/<int:pk>/', login_required(PresupuestoCategoriaUpdate.as_view(), login_url=login_url), name="cuenta-update"),


    # Asignación de Presupuesto
    #path('presupuesto-create/', AsignacionPresupuesto.as_view(), name="presupuesto-create"),
    path('presupuesto-update/<int:pk>/', login_required(AsignacionPresupuestoUpdate.as_view(), login_url=login_url), name='presupuesto-update'),
    path('ajax/load-montopresupuestario/', views.loadMontoPresupuestario, name='ajax_load_montopresupuestario'),


    # Exportar Excel
    path('cuentas-exportar/', login_required(ExportarExcelCtasPresupuestarias, login_url=login_url), name="cuentas-exportar"), 
    path('presupuesto-exportar/<int:pk>/', login_required(ExportarExcelAsignacionPresupuesto, login_url=login_url), name="presupuesto-exportar"), 
]

presupuesto/models.py
from django.db import models
from datetime import date
from django.dispatch import receiver

from insumos.models import Categoria
from departamentos.models import Departamento, Subdepartamento



class PresupuestoCategoria(models.Model):
    id_categoria = models.OneToOneField(Categoria, on_delete=models.PROTECT, verbose_name="Categoría", related_name="presupuesto_categoria")
    marco_presupuestario = models.FloatField(verbose_name="Marco Presupuestario")

    class Meta:
            ordering = ['-id']



class PresupuestoDepartamento(models.Model):
    id_presupuesto_categoria = models.ForeignKey(PresupuestoCategoria, on_delete=models.PROTECT, verbose_name="Categoría", default=None, related_name="presupuesto_dpto_categoria")
    id_departamento = models.ForeignKey(Departamento, on_delete=models.PROTECT, verbose_name="Departamento", related_name="presupuesto_dpto")
    presupuesto = models.FloatField(verbose_name="Presupuesto")
    fecha = models.DateField(default=date.today, verbose_name="Fecha")
    estado = models.BooleanField(default=True, verbose_name="Estado")  



class PresupuestoSubDepartamento(models.Model):
    id_presupuesto_categoria = models.ForeignKey(PresupuestoCategoria, on_delete=models.PROTECT, verbose_name="Categoría", default=None, related_name="presupuesto_subdpto_categoria")
    id_departamento = models.ForeignKey(Departamento, on_delete=models.PROTECT, verbose_name="Departamento", related_name="presupuesto_subdpto_dpto")
    id_subdepartamento = models.ForeignKey(Subdepartamento, on_delete=models.PROTECT, verbose_name="SubDepartamento", related_name="presupuesto_subdpto")    
    presupuesto = models.FloatField(verbose_name="Presupuesto")
    fecha = models.DateField(default=date.today, verbose_name="Fecha")
    estado = models.BooleanField(default=True, verbose_name="Estado")  

presupuesto/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Categoria, PresupuestoCategoria, PresupuestoDepartamento, PresupuestoSubDepartamento, \
                    Departamento, Subdepartamento


# Marco Presupuestario
class PresupuestoCategoriaForm(forms.ModelForm):

    id_categoria = forms.ModelChoiceField(queryset = Categoria.objects.all(), label = "Categoría", 
    empty_label = "Seleccione Categoría", widget = forms.Select(attrs={'class': 'form-select select2 col-md-2', 'required': 'true'}))

    class Meta:
        model = PresupuestoCategoria
        fields = ('id_categoria', 'marco_presupuestario')
        
        widgets = {
            'marco_presupuestario': forms.NumberInput(attrs={'class': 'form-control col-md-2', 'required': 'true'}),
        }



# Cabecera Asignación Presupuesto
class AsignacionPresupuestoForm(forms.ModelForm):
    id_presupuesto_categoria = forms.ModelChoiceField(queryset = Categoria.objects.all(), label = "Categoría", 
    empty_label = "Seleccione Categoría", widget = forms.Select(attrs={'class': 'form-select col-md-2 disabled'}))

    extra_marco_presupuestario = forms.Field(label = "Marco Presupuestario", required = False, widget = forms.TextInput(attrs={'class': 'form-control', 'disabled': 'true'}))

    class Meta:
        model = PresupuestoCategoria
        fields = ('id_presupuesto_categoria', 'extra_marco_presupuestario')



class AsignacionPresupuestoDepartamentoForm(forms.ModelForm):
    id_presupuesto_categoria = forms.ModelChoiceField(queryset = Categoria.objects.all(), label = "Categoría", 
    empty_label = "Seleccione Categoría", required=True, widget = forms.Select(attrs={'class': 'form-select disabled'}))

    id_departamento = forms.ModelChoiceField(queryset=Departamento.objects.all(), label="Departamento", 
    empty_label="Seleccione Departamento", required=True, widget = forms.Select(attrs={'class': 'form-select disabled'}))

    presupuesto = forms.FloatField(required=True, widget = forms.NumberInput(attrs={'class': 'form-control'}))

    class Meta:
        model = PresupuestoDepartamento
        fields = ('id_presupuesto_categoria', 'id_departamento', 'presupuesto')



class AsignacionPresupuestoSubDepartamentoForm(forms.ModelForm):
    id_presupuesto_categoria = forms.ModelChoiceField(queryset = Categoria.objects.all(), label = "Categoría", 
    empty_label = "Seleccione Categoría", required=True, widget = forms.Select(attrs={'class': 'form-select disabled'}))

    id_departamento = forms.ModelChoiceField(queryset=Departamento.objects.all(), label="Departamento", 
    empty_label="Seleccione Departamento", required=True, widget = forms.Select(attrs={'class': 'form-select disabled'}))

    id_subdepartamento = forms.ModelChoiceField(queryset=Subdepartamento.objects.all(), label="Sub Departamento", 
    empty_label="Seleccione Sub Departamento", required=True, widget = forms.Select(attrs={'class': 'form-select disabled'}))

    presupuesto = forms.FloatField(required=True, widget = forms.NumberInput(attrs={'class': 'form-control col-md-2'}))

    class Meta:
        model = PresupuestoSubDepartamento
        fields = ('id_presupuesto_categoria', 'id_departamento', 'id_subdepartamento', 'presupuesto')



PresupuestoDepartamentoFormSet = inlineformset_factory(
    PresupuestoCategoria, PresupuestoDepartamento, form=AsignacionPresupuestoDepartamentoForm,
    extra=0, can_delete=False
)


PresupuestoSubDepartamentoFormSet = inlineformset_factory(
    PresupuestoCategoria, PresupuestoSubDepartamento, form=AsignacionPresupuestoSubDepartamentoForm,
    extra=0, can_delete=False
)

presupuesto/templates/presupuesto/asignacionpresupuesto_form.html
{% extends 'insumos/index.html' %}

{% block content %}
    
    <div class="pagetitle">
        <h1>Presupuesto</h1>
        <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'presupuesto:cuentas-list' %}">Inicio</a></li>
            <li class="breadcrumb-item">Asignación de Presupuesto</li>
        </ol>
        </nav>
    </div>

    <section class="section">
        <div class="row">
        <div class="col-lg-12">

            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Formulario Asignación de Presupuesto</h5>

                <!-- Create/Update Asignación de Presupuesto -->
                <form method="POST" action="" novalidate autocomplete="off">
                    {% csrf_token %}


                    {% for field in form %}
                        <div class="form-group mb-2">
                            <label>{{field.label}}</label>
                            {{field}}

                            {% if field.help_text %}
                                <small style="color: grey">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endfor %}


                    <!-- inline form for detalle Presupuesto Departamento start -->

                    <!-- EXPLAINING with named_formsets.presupuestodpto y named_formsets.presupuestosubdpto as formset -->
                    <!-- Note: named_formsets is used in get_context_data function in views.py -->
                    <!-- Note: here variants is our PresupuestoDepartamentoFormSet name, used in get_named_formsets function in views.py -->

                    {% with named_formsets.presupuestodpto as formset %}
                        {{ formset.management_form }}

                        <script type="text/html" id="presupuestodpto-template">
                            <tr id="presupuestodpto-__prefix__" class= hide_all>
                                {% for fields in formset.empty_form.hidden_fields %}
                                    {{ fields }}
                                {% endfor %}
                            
                                {% for fields in formset.empty_form.visible_fields %}
                                    <td>{{fields}}</td>
                                {% endfor %}
                            </tr>
                        </script>

                        <br>



                        <div class="d-flex">
                            <div class="col-6 flex-fill">
                                <h5 class="card-title col-6">Centro de Responsabilidad</h5>
                            </div>
                        </div>


                        <table class="table table-striped table-bordered">
                                <thead class="text-center">
                                    <th scope="col">Departamento </th>
                                    <th scope="col" class="required">Monto </th>
                                    <th scope="col" class="d-none"></th>
                                </thead>
                                <tbody id="item-presupuestodpto">

                                    {% for formss in formset %}
                                        {{ formss.management_form }}
                                        <tr id="presupuestodpto-{{ forloop.counter0 }}" class= hide_all> 
                                            {{ formss.id }}
                                            {% for field in formss.visible_fields %}
                                                <td>
                                                    {{ field }}
                                                    {% for error in field.errors %}
                                                        <span style="color: red">{{ error }}</span>
                                                    {% endfor %}
                                                </td>
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                    {% endwith %}

                    <br>

                    {% with named_formsets.presupuestosubdpto as formset %}
                            {{ formset.management_form }}
    
                            <script type="text/html" id="presupuestosubdpto-template">
                                <tr id="presupuestosubdpto-__prefix__" class= hide_all>
                                    {% for fields in formset.empty_form.hidden_fields %}
                                        {{ fields }}
                                    {% endfor %}
                                
                                    {% for fields in formset.empty_form.visible_fields %}
                                        <td>{{fields}}</td>
                                    {% endfor %}
                                </tr>
                            </script>
    
                            <br>


                            <div class="d-flex">
                                <div class="col-6 flex-fill">
                                    <h5 class="card-title col-6">Centro de Costo</h5>
                                </div>                            
                            </div>


                            <table class="table table-striped">
                                <thead class="text-center">
                                    <th scope="col">Departamento </th>
                                    <th scope="col">Sub Departamento </th>
                                    <th scope="col" class="required">Monto </th>
                                    <th scope="col" class="d-none"></th>
                                </thead>
                                <tbody id="item-presupuestosubpto">
                                    {% for formss in formset %}
                                        {{ formss.management_form }}
                                        <tr id="presupuestosubpto-{{ forloop.counter0 }}" class= hide_all> 
                                            {{ formss.id }}
                                            {% for field in formss.visible_fields %}
                                                <td>
                                                    {{ field }}
                                                    {% for error in field.errors %}
                                                        <span style="color: red">{{ error }}</span>
                                                    {% endfor %}
                                                </td>
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                            <br>

                    {% endwith %}
                    <!-- inline form for Presupuesto Departamento y Sub Departamento end -->


                    <div class="col-12 text-end">
                    <input type="submit" class="btn btn-primary" value="Guardar">
                    <a href="{% url 'presupuesto:cuentas-list' %}" class="btn btn-outline-primary">Cancelar</a>
                    </div>
                </form>
                <!-- End Formulario Asignación de Presupuesto -->

            </div>
            </div>

        </div>

        <div class="col-lg-5"></div>

        </div>
    </section>

{% endblock %}


{% block jscript %}
<script>
    $(function() {

    $('.disabled').on('mousedown', function(e) {
        e.preventDefault();
    });


    let url = "{% url 'presupuesto:ajax_load_montopresupuestario' %}"
    let CtaId = $("#id_id_presupuesto_categoria").val();                // obtener id de Cuenta

        $.ajax({                                      
            url: url,                                                   // request url (localhost:8000/formularios/ajax_load_montopresupuestario/)
            data: {
              'cuenta': CtaId                                           // id de Cuenta
            },
            success: function (resp) {  
                if (resp.data)    
                    $("#id_id_presupuesto_categoria").val(resp.data.id_categoria);        
                    $("#id_extra_marco_presupuestario").val(resp.data.marco_presupuestario.toLocaleString());
            }
        });


    });
</script>
{% endblock %}

presupuesto/templates/presupuesto/presupuestocategoria_form.html
{% extends 'insumos/index.html' %}

{% load presupuesto_filters %}

{% block content %}
    
    <div class="pagetitle">
        <h1>Cuenta Presupuestaria</h1>
        <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'presupuesto:cuentas-list' %}">Inicio</a></li>
            <li class="breadcrumb-item">Formulario Cuenta Presupuestaria</li>
        </ol>
        </nav>
    </div>

    <section class="section">
        <div class="row">
        <div class="col-lg-8">

            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Formulario Cuenta Presupuestaria</h5>

                <!-- Create/Update Cuenta Presupuestaria -->
                <form method="POST" action="" novalidate autocomplete="off">
                    {% csrf_token %}
                    {{form.as_p}}

                    <div class="col-12 text-end">
                    <input type="submit" class="btn btn-primary" value="Guardar">
                    <a href="{% url 'presupuesto:cuentas-list' %}" class="btn btn-outline-primary">Cancelar</a>
                    </div>
                </form>
                <!-- End Formulario Cuenta Presupuestaria -->

            </div>
            </div>

        </div>

        <div class="col-lg-5"></div>

        </div>
    </section>


{% endblock %}

presupuesto/templates/presupuesto/presupuestocategoria_list.html
{% extends 'insumos/index.html' %}

{% load humanize %}

{% block content %}

    <div class="pagetitle">
        <h1>Cuenta Presupuestaria</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'presupuesto:cuentas-list' %}">Inicio</a></li>
                <li class="breadcrumb-item">Cuenta Presupuestaria</li>
                <li class="breadcrumb-item active">Listado</li>
            </ol>
        </nav>
    </div>

    <div class="col-12 mb-3">
        {% include 'insumos/searchbar.html' with urllist='presupuesto:cuentas-list' urlcreate='presupuesto:cuenta-create' btnnombre='Cuenta Presupuestaria' urlextra='presupuesto:cuentas-exportar' btnextra='Exportar a Excel' btnExtraVisible=True %}
    </div>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Listado de Cuentas Presupuestaria</h5>

        {% if prescategorias %}
            <table class="table table-striped table-bordered">
                <thead class="text-center">
                    <tr>
                        <th scope="col">Categoría</th>
                        <th scope="col">Marco Presupuestario</th>                    
                        <th scope="col" colspan="2"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for pcat in prescategorias %}
                    <tr class="text-center">
                        <td class="text-start">{{ pcat.id_categoria }}</td>
                        <td>$ {{ pcat.marco_presupuestario|intcomma }}</td>
                        <td class="text-center">
                            <a href="{% url 'presupuesto:cuenta-update' pcat.id %}" data-toggle="tooltip" title="Editar" class="me-2"><i class="bi bi-pencil-fill"></i></a>
                            <a href="{% url 'presupuesto:presupuesto-update' pcat.id %}" data-toggle="tooltip" title="Asignar Presupuesto" class="me-1 ms-2"><i class="bi bi-currency-dollar"></i></a>
                            <a href="{% url 'presupuesto:presupuesto-exportar' pcat.id %}" data-toggle="tooltip" title="Descargar Excel Asignación Presupuesto" class="me-1 ms-2"><i class="bi bi-file-earmark-excel-fill"></i></a>
                        </td>
                    </tr>                
                    {% endfor %}
                </tbody>
            </table>


            <div class="col-12 mb-3">
                {% include 'insumos/pagination.html'%}
            </div>


        {% else %}          
            <h3 class="text-center">No se encontraron Cuentas Presupuestarias</h3>        
        {% endif %}
        </div>
    </div>

{% endblock %}