core/urls.py
from tkinter.font import names
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('insumos.urls', namespace="insumos")),
    path('departamentos/', include('departamentos.urls', namespace="departamentos")),
    path('usuarios/', include('user.urls', namespace="usuarios")),
    path('formularios/', include('formularioInsumos.urls', namespace="formularios")),
    path('cargos/', include('cargos.urls', namespace="cargos")),
    path('formulariosr/', include('formularioSR.urls', namespace="formulariosr")),
    path('proveedores/', include('proveedores.urls', namespace="proveedores")),
    path('compras/', include('compras.urls', namespace="compras")),
    path('presupuesto/', include('presupuesto.urls', namespace="presupuestos")),
    path('cierremensual/', include('cierreMensual.urls', namespace="cierremensual")),
    path('configuraciones/', include('configuraciones.urls', namespace="configuraciones")),
    path('logs/', include('logs.urls', namespace="logs")),
    path('inventario/', include('inventario.urls', namespace="inventario")),
    path('reportes/', include('reportes.urls', namespace="reportes")),
]


handler404 = 'user.views.error_404'
handler403 = 'user.views.error_403'

departamentos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import DptoListView, DptoCreateView, DptoUpdateView, \
                  SubDptoListView, SubDptoCreateView, SubDptoUpdateView, \
                  UnidadListView, UnidadCreateView, UnidadUpdateView, \
                  ExportarExcelDptos, ExportarExcelSubDptos, ExportarExcelUnidades 

app_name = 'departamentos'
login_url = '/usuarios/login/'


urlpatterns = [
   
   #Departamentos
   path('', login_required(DptoListView.as_view(), login_url=login_url), name='dptos-list'),
   path('dptos-list/', login_required(DptoListView.as_view(), login_url=login_url), name='dptos-list'),
   path('dpto-create/', login_required(DptoCreateView.as_view(), login_url=login_url), name='dpto-create'),
   path('dpto-update/<int:pk>/', login_required(DptoUpdateView.as_view(), login_url=login_url), name='dpto-update'),


   #SubDepartamentos
   path('subdptos-list/', login_required(SubDptoListView.as_view(), login_url=login_url), name='subdptos-list'),
   path('subdpto-create/', login_required(SubDptoCreateView.as_view(), login_url=login_url), name='subdpto-create'),
   path('subdpto-update/<int:pk>/', login_required(SubDptoUpdateView.as_view(), login_url=login_url), name='subdpto-update'),


   #Unidadeds   
   path('unidades-list/', login_required(UnidadListView.as_view(), login_url=login_url), name='unidades-list'),
   path('unidad-create/', login_required(UnidadCreateView.as_view(), login_url=login_url), name='unidad-create'),
   path('unidad-update/<int:pk>/', login_required(UnidadUpdateView.as_view(), login_url=login_url), name='unidad-update'),


   # Exportar Excel
   path('departamentos-exportar/', login_required(ExportarExcelDptos, login_url=login_url), name="departamentos-exportar"),
   path('subdepartamentos-exportar/', login_required(ExportarExcelSubDptos, login_url=login_url), name="subdepartamentos-exportar"),
   path('unidades-exportar/', login_required(ExportarExcelUnidades, login_url=login_url), name="unidades-exportar"),
]

departamentos/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Departamento, Subdepartamento, Unidad
from user.models import UserProfile


class DepartamentoForm(forms.ModelForm):

    rut_jefe = forms.ModelChoiceField(queryset = UserProfile.objects.all(), to_field_name="rut", label = "Jefatura",
    empty_label = "Seleccione Jefe", required=True, widget = forms.Select(attrs={'class': 'form-select select2'}))

    rut_jefe_subrogante = forms.ModelChoiceField(queryset = UserProfile.objects.all(), to_field_name="rut", label = "Jefatura Subrogante",
    empty_label = "Seleccione Subrogante", required=False, widget = forms.Select(attrs={'class': 'form-select select2'}))


    class Meta:
        model = Departamento
        fields = ('id_dpto', 'nombre_dpto', 'rut_jefe', 'rut_jefe_subrogante')

        widgets = {
            'id_dpto': forms.NumberInput(attrs={'class': 'form-control', 'min':'0'}),
            'nombre_dpto': forms.TextInput(attrs={'class': 'form-control text-uppercase'}),
            'estado': forms.CheckboxInput(attrs={'class': 'form-check-input'})
        }



class SubDepartamentoForm(forms.ModelForm):

    departamento = forms.ModelChoiceField(queryset = Departamento.objects.all(), label = "Departamento",
    empty_label = "Seleccione Departamento", widget = forms.Select(attrs={'class': 'form-select select2',}))

    rut_jefe = forms.ModelChoiceField(queryset = UserProfile.objects.all(), to_field_name="rut", label = "Jefatura",
    empty_label = "Seleccione Jefe", widget = forms.Select(attrs={'class': 'form-select select2'}))

    rut_jefe_subrogante = forms.ModelChoiceField(queryset = UserProfile.objects.all(), to_field_name="rut", label = "Jefatura Subrogante",
    empty_label = "Seleccione Subrogante", required=False, widget = forms.Select(attrs={'class': 'form-select select2'}))


    class Meta:
        model = Subdepartamento
        fields = ('departamento', 'id_sub_dpto', 'nombre_sub_dpto', 'rut_jefe', 'rut_jefe_subrogante')

        widgets = {
            'id_sub_dpto': forms.NumberInput(attrs={'class': 'form-control', 'min':'0'}),
            'nombre_sub_dpto': forms.TextInput(attrs={'class': 'form-control text-uppercase'}),
            'estado': forms.CheckboxInput(attrs={'class': 'form-check-input'})
        }



class UnidadForm(forms.ModelForm):

    subdepartamento = forms.ModelChoiceField(queryset = Subdepartamento.objects.all(), label = "Sub Departamento",
    empty_label = "Seleccione Sub Departamento", widget = forms.Select(attrs={'class': 'form-select select2'}))

    rut_jefe = forms.ModelChoiceField(queryset = UserProfile.objects.all(), to_field_name="rut", label = "Jefatura",
    empty_label = "Seleccione Jefe", widget = forms.Select(attrs={'class': 'form-select select2'}))

    rut_jefe_subrogante = forms.ModelChoiceField(queryset = UserProfile.objects.all(), to_field_name="rut", label = "Jefatura Subrogante",
    empty_label = "Seleccione Subrogante", required=False, widget = forms.Select(attrs={'class': 'form-select select2'}))


    class Meta:
        model = Unidad
        fields = ('subdepartamento', 'id_unidad', 'nombre_unidad', 'rut_jefe', 'rut_jefe_subrogante')

        widgets = {
            'id_unidad': forms.NumberInput(attrs={'class': 'form-control', 'min':'0'}),
            'nombre_unidad': forms.TextInput(attrs={'class': 'form-control text-uppercase'}),
            'estado': forms.CheckboxInput(attrs={'class': 'form-check-input'})
        }

departamentos/views.py
import xlwt
import datetime

from msilib.schema import ListView
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.conf import settings

from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required

from departamentos.templatetags import departamentos_filters
from .forms import DepartamentoForm, SubDepartamentoForm, UnidadForm
from .models import Departamento, Subdepartamento, Unidad
from user.models import UserProfile, User
from logs.models import Log


#   Departamento 
class DptoListView(PermissionRequiredMixin, ListView):
    permission_required = ("departamentos.view_departamento")

    model = Departamento  
    context_object_name = 'departamentos'
    
    paginate_by = 10


    def get_queryset(self):
        # QuerySet por defecto
        queryset = Departamento.objects.all()
        # Verifica si el formulario fue enviado o no 
        if self.request.GET.keys():
            # Verifica campo de búsqueda
            if self.request.GET.get('buscar') != '':
                keyword = self.request.GET.get('buscar')

                # Query filtrado por término de búsqueda 
                filtro_user = User.objects.filter(first_name__icontains=keyword)
                filtro_funcionario = UserProfile.objects.filter(user__in=filtro_user).values_list('rut')
                
                queryset = Departamento.objects.filter( 
                                Q(id_dpto__icontains=keyword) |                                                     # Código Departamento
                                Q(nombre_dpto__icontains=keyword) |                                                 # Nombre Departamento
                                Q(rut_jefe__icontains=keyword) |                                                    # Rut Jefe
                                Q(rut_jefe_subrogante__icontains=keyword) |                                         # Rut Jefe Subrogante
                                Q(rut_jefe__in = filtro_funcionario) |                                              # Nombre Jefe
                                Q(rut_jefe_subrogante__in = filtro_funcionario)                                     # Nombre Jefe Subrogante
                        )
        return queryset



class DptoCreateView(PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    permission_required = ("departamentos.add_departamento")

    model = Departamento
    form_class = DepartamentoForm


    def post(self, request):
        if request.method == 'POST':
            form = DepartamentoForm(request.POST)
            if form.is_valid():
                
                dpto = form.save(commit=False)
                dpto.nombre_dpto = request.POST.get('nombre_dpto').upper()
                dpto.rut_jefe = request.POST.get('rut_jefe')
                dpto.rut_jefe_subrogante = request.POST.get('rut_jefe_subrogante')
                dpto.save()

                Log.InsertarLog(self.request.user, 'Se creó un nuevo Departamento Id ' + str(self.object.pk) + " - " + dpto.nombre_dpto, 0)        

                messages.success(request, ("Departamento fue creado con éxito."))
                return HttpResponseRedirect(reverse_lazy('departamentos:dptos-list'))



class DptoUpdateView(PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    permission_required = ("departamentos.change_departamento")

    model = Departamento
    form_class = DepartamentoForm


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            dpto = form.save(commit=False)
            dpto.nombre_dpto = self.request.POST.get('nombre_dpto').upper()
            dpto.rut_jefe = self.request.POST.get('rut_jefe')
            dpto.rut_jefe_subrogante = self.request.POST.get('rut_jefe_subrogante')        
            dpto.save()

            Log.InsertarLog(self.request.user, 'Se actualizó el Departamento Id ' + str(dpto.id_dpto) + " a " + dpto.nombre_dpto, 0)

            messages.success(request, ("Departamento fue actualizado con éxito."))
            return HttpResponseRedirect(reverse_lazy('departamentos:dptos-list'))
        else:
            return HttpResponseRedirect(reverse_lazy('departamentos:dpto-update', kwargs={'pk': self.object.pk}))


#   Sub Departamento 
class SubDptoListView(PermissionRequiredMixin, ListView):
    permission_required = ("departamentos.view_subdepartamento")

    model = Subdepartamento    
    context_object_name = 'subdepartamentos'
    
    paginate_by = 10
    ordering = ['id_sub_dpto']


    def get_queryset(self):
        # QuerySet por defecto
        queryset = Subdepartamento.objects.all()
        # Check the form value is submitted or not
        if self.request.GET.keys():
            # Verifica campo de búsqueda
            if self.request.GET.get('buscar') != '':
                keyword = self.request.GET.get('buscar')
                
                # Query filtrado por término de búsqueda 

                filtro_user = User.objects.filter(first_name__icontains=keyword)
                filtro_funcionario = UserProfile.objects.filter(user__in=filtro_user).values_list('rut')
                
                queryset = Subdepartamento.objects.filter( 
                                Q(id_sub_dpto__icontains=keyword) |
                                Q(nombre_sub_dpto__icontains=keyword) |
                                Q(departamento__nombre_dpto__icontains=keyword) |
                                Q(rut_jefe__icontains=keyword) |
                                Q(rut_jefe_subrogante__icontains=keyword) | 
                                Q(rut_jefe__in=filtro_funcionario) |
                                Q(rut_jefe_subrogante__in=filtro_funcionario)
                        )
        return queryset



class SubDptoCreateView(PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    permission_required = ("departamentos.add_subdepartamento")

    model = Subdepartamento
    form_class = SubDepartamentoForm


    def post(self, request):
        if request.method == 'POST':
            form = SubDepartamentoForm(request.POST)

            if form.is_valid():                
                subdpto = form.save(commit=False)
                subdpto.nombre_sub_dpto = self.request.POST.get('nombre_sub_dpto').upper()
                subdpto.rut_jefe = request.POST.get('rut_jefe')
                subdpto.rut_jefe_subrogante = request.POST.get('rut_jefe_subrogante')
                subdpto.save()

                Log.InsertarLog(self.request.user, 'Se creó un nuevo Subdepartamento Id ' + str(self.object.pk) + " a " + subdpto.nombre_sub_dpto, 0)

                messages.success(request, ("Subdepartamento fue creado con éxito."))
                return HttpResponseRedirect(reverse_lazy('departamentos:subdptos-list'))



class SubDptoUpdateView(PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    permission_required = ("departamentos.change_subdepartamento")

    model = Subdepartamento
    form_class = SubDepartamentoForm


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            subdpto = form.save(commit=False)
            subdpto.nombre_sub_dpto = self.request.POST.get('nombre_sub_dpto').upper()
            subdpto.rut_jefe = self.request.POST.get('rut_jefe')
            subdpto.rut_jefe_subrogante = self.request.POST.get('rut_jefe_subrogante')      
            subdpto.save()

            Log.InsertarLog(self.request.user, 'Se actualizó el Subdepartamento Id ' + str(subdpto.id_sub_dpto) + " a " + subdpto.nombre_sub_dpto, 0)

            messages.success(request, ("Subdepartamento fue creado con éxito."))
        return HttpResponseRedirect(reverse_lazy('departamentos:subdptos-list'))



#   Unidad 
class UnidadListView(PermissionRequiredMixin, ListView):
    permission_required = ("departamentos.view_unidad")

    model = Unidad    
    context_object_name = 'unidades'
    
    paginate_by = 10
    ordering = ['id_unidad']


    def get_queryset(self):
        # QuerySet por defecto
        queryset = Unidad.objects.all()
        # Check the form value is submitted or not
        if self.request.GET.keys():
            # Verifica campo de búsqueda
            if self.request.GET.get('buscar') != '':
                keyword = self.request.GET.get('buscar')
                
                # Query filtrado por término de búsqueda 
                filtro_user = User.objects.filter(first_name__icontains=keyword)
                filtro_funcionario = UserProfile.objects.filter(user__in=filtro_user).values_list('rut')
                
                queryset = Unidad.objects.filter( 
                                Q(id_unidad__icontains=keyword) |
                                Q(nombre_unidad__icontains=keyword) |
                                Q(subdepartamento__nombre_sub_dpto__icontains=keyword) |
                                Q(rut_jefe__icontains=keyword) |
                                Q(rut_jefe_subrogante__icontains=keyword)  | 
                                Q(rut_jefe__in=filtro_funcionario) |
                                Q(rut_jefe_subrogante__in=filtro_funcionario)
                        )
        return queryset



class UnidadCreateView(PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    permission_required = ("departamentos.add_unidad")
    model = Unidad
    form_class = UnidadForm


    def post(self, request):
        if request.method == 'POST':
            form = UnidadForm(request.POST)

departamentos/templates/departamentos/departamento_form.html
{% extends 'insumos/index.html' %}

{% block content %}

      <div class="pagetitle">
        <h1>Departamento</h1>
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Inicio</a></li>
            <li class="breadcrumb-item">Departamento</li>
          </ol>
        </nav>
      </div><!-- End Page Title -->
  
      <section class="section">
        <div class="row">
          <div class="col-lg-8">
  
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Formulario Departamento</h5>
  
                <!-- Create/Update Departamentos -->
                <form method="POST" action="" novalidate autocomplete="off">
                    {% csrf_token %}
                    {{form.as_p}}

                    <div class="col-12 text-end">
                      <input type="submit" class="btn btn-primary" value="Guardar">
                      <a href="{% url 'departamentos:dptos-list' %}" class="btn btn-outline-primary">Cancelar</a>
                    </div>
                </form>
                <!-- End Formulario Departamentos -->
  
              </div>
            </div>
  
          </div>
  
          <div class="col-lg-5"></div>
          
        </div>
      </section>

{% endblock %}

departamentos/templates/departamentos/departamento_list.html
{% extends 'insumos/index.html' %}

{% load departamentos_filters %}

{% block content %}
    
    <div class="pagetitle">
      <h1>Departamentos</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'departamentos:dptos-list' %}">Inicio</a></li>
          <li class="breadcrumb-item">Departamentos</li>
          <li class="breadcrumb-item active">Listado</li>
        </ol>
      </nav>
    </div>

    <div class="col-12 mb-3">
      {% include 'insumos/searchbar.html' with urllist='departamentos:dptos-list' urlcreate='departamentos:dpto-create' btnnombre='Agregar Departamento' urlextra='departamentos:departamentos-exportar' btnextra='Exportar a Excel' btnExtraVisible=True %}
  </div>

    <div class="card">
        <div class="card-body">
          <h5 class="card-title">Listado de Departamentos</h5>

        {% if departamentos %}
          <table class="table table-striped table-bordered">
            <thead class="text-center">
                <tr>
                    <th scope="col">Código Departamento</th>
                    <th scope="col">Nombre Departamento</th>
                    <th scope="col">Jefatura</th>
                    <th scope="col">Subrogante</th>
                    <th scope="col">Estado</th>
                    <th scope="col" colspan="2"></th>
                </tr>
            </thead>
            <tbody>
                {% for dpto in departamentos %}
                <tr>
                    <td class="text-center">{{ dpto.id_dpto|safe }}</td>
                    <td>{{ dpto.nombre_dpto|upper }}</td>
                    <td>{{ dpto.rut_jefe|get_nombre_jefe }}</td>
                    <td>{{ dpto.rut_jefe_subrogante|get_nombre_jefe|default_if_none:"" }}</td>
                    <td class="text-center">{{ dpto.get_estado_dpto }}</td>
                    <td class="text-center">
                      <a href="{% url 'departamentos:dpto-update' dpto.id %}" data-toggle="tooltip" title="Editar" class="me-1"><i class="bi bi-pencil-fill"></i></a>
                    </td>
                </tr>                
                {% endfor %}
            </tbody>
          </table>

          
          <div class="col-12 mb-3">
            {% include 'insumos/pagination.html'%}
          </div>


        {% else %}          
          <h3 class="text-center">No se encontraron Departamentos</h3>        
        {% endif %}
        </div>
    </div>

{% endblock %}

departamentos/templates/departamentos/subdepartamento_form.html
{% extends 'insumos/index.html' %}

{% block content %}

<div class="pagetitle">
    <h1>Sub Departamento</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Inicio</a></li>
        <li class="breadcrumb-item">Sub Departamento</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section">
    <div class="row">
      <div class="col-lg-8">

        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Formulario Sub Departamento</h5>

            <!-- Create/Update Categorías -->
            <form method="POST" action="" novalidate autocomplete="off">
                {% csrf_token %}
                {{form.as_p}}

                <div class="col-12 text-end">
                  <input type="submit" class="btn btn-primary" value="Guardar">
                  <a href="{% url 'departamentos:subdptos-list' %}" class="btn btn-outline-primary">Cancelar</a>
                </div>
            </form>
            <!-- End Formulario Categorías -->

          </div>
        </div>

      </div>

      <div class="col-lg-5"></div>
      
    </div>
  </section>

{% endblock %}

departamentos/templates/departamentos/subdepartamento_list.html
{% extends 'insumos/index.html' %}

{% load departamentos_filters %}

{% block content %}
    
    <div class="pagetitle">
      <h1>Sub Departamentos</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'departamentos:subdptos-list' %}">Inicio</a></li>
          <li class="breadcrumb-item">Departamentos</li>
          <li class="breadcrumb-item active">Listado</li>
        </ol>
      </nav>
    </div>

    <div class="col-12 mb-3">
      {% include 'insumos/searchbar.html' with urllist='departamentos:subdptos-list' urlcreate='departamentos:subdpto-create' btnnombre='Agregar Sub Departamento' urlextra='departamentos:subdepartamentos-exportar' btnextra='Exportar a Excel' btnExtraVisible=True %}
    </div>

    <div class="card">
        <div class="card-body">
          <h5 class="card-title">Listado de Sub Departamentos</h5>

        {% if subdepartamentos %}
          <table class="table table-striped table-bordered">
            <thead class="text-center">
                <tr>
                    <th scope="col">Código Sub Departamento</th>
                    <th scope="col">Departamento</th>
                    <th scope="col">Nombre Sub Departamento</th>
                    <th scope="col">Jefatura</th>
                    <th scope="col">Subrogante</th>
                    <th scope="col">Estado</th>
                    <th scope="col" colspan="2"></th>
                </tr>
            </thead>
            <tbody>
                {% for subdpto in subdepartamentos %}
                <tr>
                    <td class="text-center">{{ subdpto.id_sub_dpto|safe }}</td>
                    <td>{{ subdpto.departamento }}</td>
                    <td>{{ subdpto.nombre_sub_dpto }}</td>
                    <td class="text-center">{{ subdpto.rut_jefe|get_nombre_jefe }}</td>
                    <td class="text-center">{{ subdpto.rut_jefe_subrogante|get_nombre_jefe|default_if_none:"" }}</td>
                    <td class="text-center">{{ subdpto.get_estado_subdpto }}</td>
                    <td class="text-center">
                      <a href="{% url 'departamentos:subdpto-update' subdpto.id %}" data-toggle="tooltip" title="Editar" class="me-1"><i class="bi bi-pencil-fill"></i></a>
                    </td>
                </tr>                
                {% endfor %}
            </tbody>
          </table>

          
          <div class="col-12 mb-3">
            {% include 'insumos/pagination.html'%}
          </div>


        {% else %}          
          <h3 class="text-center">No se encontraron Sub Departamentos</h3>        
        {% endif %}
        </div>
    </div>

{% endblock %}

departamentos/templates/departamentos/unidad_form.html
{% extends 'insumos/index.html' %}

{% block content %}

<div class="pagetitle">
    <h1>Unidad</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Inicio</a></li>
        <li class="breadcrumb-item">Unidad</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section">
    <div class="row">
      <div class="col-lg-8">

        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Formulario Unidad</h5>

            <!-- Create/Update Categorías -->
            <form method="POST" action="" novalidate autocomplete="off">
                {% csrf_token %}
                {{form.as_p}}

                <div class="col-12 text-end">
                  <input type="submit" class="btn btn-primary" value="Guardar">
                  <a href="{% url 'departamentos:unidades-list' %}" class="btn btn-outline-primary">Cancelar</a>
                </div>
            </form>
            <!-- End Formulario Categorías -->

          </div>
        </div>

      </div>

      <div class="col-lg-5"></div>
      
    </div>
  </section>

{% endblock %}

departamentos/templates/departamentos/unidad_list.html
{% extends 'insumos/index.html' %}

{% load departamentos_filters %}

{% block content %}
    
    <div class="pagetitle">
      <h1>Unidades/Secciones</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'departamentos:unidades-list' %}">Inicio</a></li>
          <li class="breadcrumb-item">Unidades/Secciones</li>
          <li class="breadcrumb-item active">Listado</li>
        </ol>
      </nav>
    </div>

    <div class="col-12 mb-3">
      {% include 'insumos/searchbar.html' with urllist='departamentos:unidades-list' urlcreate='departamentos:unidad-create' btnnombre='Agregar Unidad' urlextra='departamentos:unidades-exportar' btnextra='Exportar a Excel' btnExtraVisible=True %}
  </div>

    <div class="card">
        <div class="card-body">
          <h5 class="card-title">Listado de Unidades/Secciones</h5>

        {% if unidades %}
          <table class="table table-striped table-bordered">
            <thead class="text-center">
                <tr>
                    <th scope="col">Código Unidad</th>
                    <th scope="col">Sub Departamento</th>
                    <th scope="col">Nombre Unidad</th>
                    <th scope="col">Jefatura</th>
                    <th scope="col">Subrogante</th>
                    <th scope="col">Estado</th>
                    <th scope="col" colspan="2"></th>
                </tr>
            </thead>
            <tbody>
                {% for unidad in unidades %}
                <tr>
                    <td class="text-center">{{ unidad.id_unidad|safe }}</td>
                    <td>{{ unidad.subdepartamento }}</td>
                    <td>{{ unidad.nombre_unidad }}</td>
                    <td>{{ unidad.rut_jefe|get_nombre_jefe }}</td>
                    <td>{{ unidad.rut_jefe_subrogante|get_nombre_jefe|default_if_none:"" }}</td>
                    <td class="text-center">{{ unidad.get_estado_unidad }}</td>
                    <td class="text-center">
                      <a href="{% url 'departamentos:unidad-update' unidad.id %}" data-toggle="tooltip" title="Editar" class="me-1"><i class="bi bi-pencil-fill"></i></a>
                      <!--<a href="{ % url 'cargos:cargo-delete' cargo.id % }" class="ms-1">Eliminar</a>-->
                    </td>
                </tr>                
                {% endfor %}
            </tbody>
          </table>

          
          <div class="col-12 mb-3">
            {% include 'insumos/pagination.html'%}
          </div>


        {% else %}          
          <h3 class="text-center">No se encontraron Unidades</h3>        
        {% endif %}
        </div>
    </div>

{% endblock %}